
plugins {
    id 'java-library'
    id 'maven-publish'
}

// sourceCompatibility = JavaVersion.VERSION_17
// targetCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.squareup:javapoet:1.13.0"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.google.testing.compile:compile-testing:0.21.0'
    testImplementation 'com.google.truth:truth:1.4.4'
}

test {
    useJUnit()
}

publishing {
    publications {
        maven(MavenPublication) {
            // Use jitpack format for publishing to mavenLocal
            groupId = 'com.github.Frc5572'
            artifactId = 'RobotTools'
            version = 'test-SNAPSHOT'

            from components.java
        }
    }
}
