name: CI
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    env:
      # This line prevents the action from running after an automated push.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v2 minimum required
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          tool_name: 'testtool'
          fail_on_error: true
          filter_mode: nofilter
          level: error
          checkstyle_config: checks.xml
          checkstyle_version: '9.2.1'
  spell_check:
    name: Spell Check
    runs-on: ubuntu-latest
    env:
      # This line prevents the action from running after an automated push.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v2 minimum required
      - name: Run Spell Check
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
  merge_conflict_job:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    env:
      # This line prevents the action from running after an automated push.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the source code so there are some files to look at.
      - uses: actions/checkout@v3
      # Run the actual merge conflict finder
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0